import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Privacy Policy — AskFirst',
  description:
    'How AskFirst collects, uses, shares, and protects your personal data when you use our human-in-the-loop approval API and website.',
}

export default function PrivacyPage() {
  return (
    <>
      <nav>
        <Link href="/" className="logo-link">
          <img src="/logoaiskfirst.svg" alt="AskFirst Logo" className="logo-img" />
        </Link>
        <div className="nav-links">
          <Link href="/#how">How it works</Link>
          <Link href="/#integrations">Integrations</Link>
          <Link href="/#pricing">Pricing</Link>
        </div>
        <Link href="/#waitlist" className="nav-cta">Join waitlist</Link>
      </nav>

      <header className="legal-hero">
        <div className="legal-hero-grid" />
        <div className="legal-hero-glow" />
        <span className="legal-eyebrow">Legal</span>
        <h1>Privacy Policy</h1>
        <p className="legal-updated">Last updated: June 16, 2026</p>
      </header>

      <main className="legal-wrap">
        <aside className="toc">
          <div className="toc-title">On this page</div>
          <ol>
            <li><a href="#overview">Overview</a></li>
            <li><a href="#who">Who we are</a></li>
            <li><a href="#collect">What we collect</a></li>
            <li><a href="#use">How we use it</a></li>
            <li><a href="#bases">Legal bases</a></li>
            <li><a href="#sharing">Sharing &amp; processors</a></li>
            <li><a href="#retention">Data retention</a></li>
            <li><a href="#security">Security</a></li>
            <li><a href="#transfers">International transfers</a></li>
            <li><a href="#rights">Your rights</a></li>
            <li><a href="#cookies">Cookies</a></li>
            <li><a href="#children">Children</a></li>
            <li><a href="#changes">Changes</a></li>
            <li><a href="#contact">Contact</a></li>
          </ol>
        </aside>

        <article className="legal-content">
          <p className="intro">
            This Privacy Policy explains how AskFirst collects, uses, shares, and protects personal
            data when you visit <code>aiskfirst.com</code>, join our waitlist, or use the AskFirst
            API and related services (the &quot;Service&quot;). We aim to collect only what we need
            to run the Service well.
          </p>

          <h2 id="overview"><span className="num">01</span> Overview</h2>
          <p>
            AskFirst is a human-in-the-loop approval layer for AI agents. To provide it, we process
            a small amount of personal data — primarily email addresses and the approval-related
            information you choose to send through the Service. We do not sell your personal data.
          </p>

          <h2 id="who"><span className="num">02</span> Who we are</h2>
          <p>
            The Service is operated by AskFirst (&quot;AskFirst&quot;, &quot;we&quot;,
            &quot;us&quot;). For privacy questions, contact us at{' '}
            <a href="mailto:privacy@aiskfirst.com">privacy@aiskfirst.com</a>. Where
            data-protection law applies, we act as the <strong>controller</strong> for data about
            our website visitors and account holders, and as a <strong>processor</strong> for the
            approval content you submit on behalf of your own users.
          </p>

          <h2 id="collect"><span className="num">03</span> What we collect</h2>
          <table className="data-table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Examples</th>
                <th>Source</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Waitlist data</td>
                <td>Email address you submit to join the waitlist</td>
                <td>You</td>
              </tr>
              <tr>
                <td>Account data</td>
                <td>Name, email, organization, and login credentials (when accounts launch)</td>
                <td>You</td>
              </tr>
              <tr>
                <td>Approval content</td>
                <td>
                  Questions, context, metadata, decisions, and timestamps in your Approval Requests;
                  Approver email addresses you provide
                </td>
                <td>You / your Agent</td>
              </tr>
              <tr>
                <td>Audit records</td>
                <td>Who approved or denied what, when, and the resulting decision log</td>
                <td>Generated by the Service</td>
              </tr>
              <tr>
                <td>Billing data</td>
                <td>
                  Plan, billing contact, and payment confirmation (card details are handled by our
                  payment processor, not stored by us)
                </td>
                <td>You / payment processor</td>
              </tr>
              <tr>
                <td>Technical data</td>
                <td>IP address, device/browser type, API request logs, and basic usage analytics</td>
                <td>Automatically</td>
              </tr>
            </tbody>
          </table>
          <div className="callout">
            <p>
              Please avoid putting sensitive personal data (such as health, financial, or
              government-ID details) into Approval Request questions or context unless it is
              necessary and you have a lawful basis to do so.
            </p>
          </div>

          <h2 id="use"><span className="num">04</span> How we use it</h2>
          <ul>
            <li>
              To provide the Service — routing Approval Requests, notifying Approvers, returning
              decisions, and keeping audit logs;
            </li>
            <li>To manage the waitlist and send you a notification when we launch;</li>
            <li>To create and administer your account and process payments;</li>
            <li>To secure the Service, prevent abuse, and debug issues;</li>
            <li>To understand usage and improve features and reliability;</li>
            <li>
              To communicate with you about the Service, and (where permitted) about product updates
              — you can opt out of marketing at any time;
            </li>
            <li>
              To comply with legal obligations and enforce our{' '}
              <Link href="/terms">Terms</Link>.
            </li>
          </ul>

          <h2 id="bases"><span className="num">05</span> Legal bases (where GDPR applies)</h2>
          <ul>
            <li>
              <strong>Contract</strong> — to provide the Service you&apos;ve requested and manage
              your account;
            </li>
            <li>
              <strong>Consent</strong> — for joining the waitlist and for optional marketing emails;
            </li>
            <li>
              <strong>Legitimate interests</strong> — to secure, maintain, and improve the Service,
              where not overridden by your rights;
            </li>
            <li>
              <strong>Legal obligation</strong> — to meet accounting, tax, and compliance
              requirements.
            </li>
          </ul>

          <h2 id="sharing"><span className="num">06</span> Sharing &amp; processors</h2>
          <p>
            We do not sell your personal data. We share it only with service providers
            (&quot;sub-processors&quot;) who help us run the Service, under appropriate contracts,
            and where required by law. Typical categories include:
          </p>
          <ul>
            <li>
              <strong>Email &amp; notification providers</strong> — to deliver waitlist
              confirmations and Approval Request notifications;
            </li>
            <li>
              <strong>Messaging integrations</strong> — e.g., Slack, when you enable them;
            </li>
            <li>
              <strong>Payment processor</strong> — to handle subscriptions and billing;
            </li>
            <li>
              <strong>Hosting &amp; infrastructure</strong> — to host the Service and store data;
            </li>
            <li>
              <strong>Analytics &amp; error monitoring</strong> — to keep the Service reliable.
            </li>
          </ul>
          <p>
            At present we use <strong>Resend</strong> to deliver waitlist confirmations and email
            notifications, <strong>Slack</strong> to deliver notifications when you enable that
            integration, a third-party <strong>payment processor</strong> for paid plans, and a{' '}
            <strong>hosting provider</strong> to run the Service. We keep this list current as our
            providers change. We may also disclose data if required by law or to protect our rights,
            users, or the public.
          </p>

          <h2 id="retention"><span className="num">07</span> Data retention</h2>
          <p>
            We keep personal data only as long as needed for the purposes above. Waitlist emails are
            kept until launch and then either migrated to your account (with notice) or deleted on
            request. Audit logs are retained for the period associated with your plan and are deleted
            or anonymized within 12 months of account closure. We respond to deletion requests
            within 30 days unless a longer period is required by law.
          </p>

          <h2 id="security"><span className="num">08</span> Security</h2>
          <p>
            We use reasonable technical and organizational measures — such as encryption in transit,
            access controls, and API-key authentication — to protect personal data. No method of
            transmission or storage is completely secure, so we cannot guarantee absolute security.
            If a breach affects your data, we will notify you as required by law.
          </p>

          <h2 id="transfers"><span className="num">09</span> International transfers</h2>
          <p>
            We and our providers may process data in countries other than yours. Where required, we
            use appropriate safeguards (such as standard contractual clauses) to protect data
            transferred across borders.
          </p>

          <h2 id="rights"><span className="num">10</span> Your rights</h2>
          <p>
            Depending on where you live (e.g., under the EU/UK GDPR or similar laws), you may have
            the right to:
          </p>
          <ul>
            <li>Access the personal data we hold about you;</li>
            <li>Correct inaccurate data or complete incomplete data;</li>
            <li>Delete your data (&quot;right to be forgotten&quot;);</li>
            <li>Restrict or object to certain processing;</li>
            <li>Receive your data in a portable format;</li>
            <li>Withdraw consent at any time (including unsubscribing from emails);</li>
            <li>Lodge a complaint with your local data-protection authority.</li>
          </ul>
          <p>
            To exercise any of these, email{' '}
            <a href="mailto:privacy@aiskfirst.com">privacy@aiskfirst.com</a>. We will respond
            within the timeframe required by applicable law.
          </p>

          <h2 id="cookies"><span className="num">11</span> Cookies</h2>
          <p>
            Our website currently uses only the minimal cookies and similar technologies needed to
            operate the site and submit the waitlist form. We do not currently set advertising
            cookies or third-party tracking. If we add analytics or marketing cookies in the future,
            we will describe them here and provide a consent mechanism where required. You can
            control cookies through your browser settings.
          </p>

          <h2 id="children"><span className="num">12</span> Children</h2>
          <p>
            The Service is not directed to children under 16, and we do not knowingly collect their
            personal data. If you believe a child has provided us data, contact us and we will
            delete it.
          </p>

          <h2 id="changes"><span className="num">13</span> Changes to this policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will revise the &quot;Last
            updated&quot; date above and, for material changes, provide additional notice where
            appropriate.
          </p>

          <h2 id="contact"><span className="num">14</span> Contact</h2>
          <p>
            Questions or requests about your privacy? Contact{' '}
            <a href="mailto:privacy@aiskfirst.com">privacy@aiskfirst.com</a>.
          </p>
        </article>
      </main>

      <footer>
        <Link href="/" className="logo-link">
          <img src="/logoaiskfirst.svg" alt="AskFirst Logo" className="logo-img" />
        </Link>
        <div className="footer-links">
          <Link href="/terms">Terms &amp; Conditions</Link>
          <Link href="/privacy">Privacy Policy</Link>
        </div>
        <p>© 2025 AskFirst. Built for AI agent builders.</p>
      </footer>
    </>
  )
}
